// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLx_S_gm-KJchKQKp076xGKh_aOAJA0js',
    appId: '1:535787803432:web:ba59b1745cb0f5ce6f761d',
    messagingSenderId: '535787803432',
    projectId: 'voice-app-123',
    authDomain: 'voice-app-123.firebaseapp.com',
    storageBucket: 'voice-app-123.appspot.com',
    measurementId: 'G-FBR57S2LZT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc7IzC8YShcZSHE7wMlGZXEEFtMIe2kdM',
    appId: '1:535787803432:android:2026984ebe15efbc6f761d',
    messagingSenderId: '535787803432',
    projectId: 'voice-app-123',
    storageBucket: 'voice-app-123.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClnZdvV2V2DhvyAeqL1jLCfhFe6ib8Upo',
    appId: '1:535787803432:ios:544850c9aec0cfd66f761d',
    messagingSenderId: '535787803432',
    projectId: 'voice-app-123',
    storageBucket: 'voice-app-123.appspot.com',
    iosClientId: '535787803432-60n5ifphh5d66e90ohn2gkpu16f986gl.apps.googleusercontent.com',
    iosBundleId: 'com.example.voiceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClnZdvV2V2DhvyAeqL1jLCfhFe6ib8Upo',
    appId: '1:535787803432:ios:34807c213f30a4e76f761d',
    messagingSenderId: '535787803432',
    projectId: 'voice-app-123',
    storageBucket: 'voice-app-123.appspot.com',
    iosClientId: '535787803432-7qa03irbh9rjuqvej7u28507qmqjmhbk.apps.googleusercontent.com',
    iosBundleId: 'com.example.voiceApp.RunnerTests',
  );
}
